version: '3.7'
services:
  pyspark:
    container_name: jupyter-pyspark
    image: jupyter/pyspark-notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebook:/home/jovyan/work
    ports:
      - 10000:8888
    #######################################
    #               Database              #
    #######################################
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
        - 27017:27017
  
  #######################################
  #            Mongo Express            #
  #######################################
  mongoexpress:
      image: "mongo-express:latest"
      container_name: "mongo_express"
      ports:
          - "9001:8081"
      links:
          - mongodb:mongo