spring:
  elasticsearch:
    rest:
      password: changeme
      username: elastic
  data:
    mongodb:
      host: localhost
      port: 27017
      database: epidemics
  main:
    allow-bean-definition-overriding: true